// <auto-generated />
using System;
using FishDataSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FishDataSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240105213848_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Fish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BottDepthM")
                        .HasColumnType("numeric")
                        .HasColumnName("bottdepthm");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datetime");

                    b.Property<double>("Individuals")
                        .HasColumnType("double precision")
                        .HasColumnName("individuals");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Parameter")
                        .HasColumnType("text")
                        .HasColumnName("parameter");

                    b.Property<string>("Project")
                        .HasColumnType("text")
                        .HasColumnName("project");

                    b.Property<string>("Quality")
                        .HasColumnType("text")
                        .HasColumnName("quality");

                    b.Property<double>("SampleId")
                        .HasColumnType("double precision")
                        .HasColumnName("sampleid");

                    b.Property<string>("Species")
                        .HasColumnType("text")
                        .HasColumnName("species");

                    b.Property<string>("Station")
                        .HasColumnType("text")
                        .HasColumnName("station");

                    b.Property<string>("Tissue")
                        .HasColumnType("text")
                        .HasColumnName("tissue");

                    b.Property<string>("Trip")
                        .HasColumnType("text")
                        .HasColumnName("trip");

                    b.Property<string>("Units")
                        .HasColumnType("text")
                        .HasColumnName("units");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("fishes");
                });
#pragma warning restore 612, 618
        }
    }
}
